### ISSUE TITLE
[BUG] Cannot download multiple .eml attachments

### ISSUE THREAD

**Issue by codyproxy** [barbushin/php-imap#391]
**Environment:**
 - PHP IMAP version: 3.0.30
 - PHP Version: 7.1.3
 - Type of execution: Web Server

**Describe the bug**
When i fetch an email which has more than 1 .eml attachment files (for example, 2 of them), when i use 'getAttachments' to store the attachments as files, the function only returns 1 .eml attachment, always with the filename 'rfc822.eml'. It seems that it only keeps the last one.

**To Reproduce**
- Fetch a mail with multiple .eml attachments.
- Save them directly as a file, or print the result of 'getAttachments'.

The used code:
```php
$mailbox = new PhpImap\Mailbox(
	'{my-host:993/imap/ssl}INBOX', // IMAP server and mailbox folder
	'my-username', // Username for the before configured mailbox
	'my-password', // Password for the before configured username
	$_SERVER['DOCUMENT_ROOT'] . '/test', // Directory, where attachments will be saved (optional)
	'UTF-8' // Server encoding (optional)
);

$mailsIds = $mailbox->searchMailbox('UNSEEN');

if (!empty($mailsIds)) {

    $mail = $mailbox->getMail($mailsIds[0], false);

    if ($mail->hasAttachments()) {

        print_r($mail->getAttachments());
        die();
    }
}
```

**Expected behavior**
All .eml files to be stored as files and available in 'getAttachments' as a normal attachment.

**Comment by fabriziobertoglio1987** [comment]
the problem must be related on how [addAttachment()](https://github.com/barbushin/php-imap/blob/62664de68468d67050e99ae0ece4ccaf0211155a/src/PhpImap/IncomingMail.php#L79) adds each one of those attachments. 

```php
public function addAttachment(IncomingMailAttachment $attachment)
  {
     $this->attachments[$attachment->id] = $attachment;
  }
```

`$this->attachments` is an array an the attachment are saved based on the `$attachment->id`. If different attachments have the same `id`, they will be overwritten, but this should not be the case as usually `id`s are unique.

The issue must be more complex, but I decided to post and start an interaction with codyproxy.

Thanks
I wish you a good evening
Fabrizio

**Comment by Sebi94nbg** [comment]
Sorry, but I can't reproduce this issue with the latest code.

My used code to test this:

```php
<?php
        require_once __DIR__ . '/vendor/autoload.php';
        use PhpImap\Mailbox;
        use PhpImap\Exceptions\ConnectionException;

        $mailbox = "{imap.gmail.com:993/imap/ssl}INBOX";
        $mailbox_username = "some@gmail.com";
        $mailbox_password = "*********";

        echo "Trying to connect to '$mailbox'...\n";

        $mbox_connection = new Mailbox($mailbox, $mailbox_username, $mailbox_password, __DIR__.'/files/');

        try {
                $mbox_connection->setServerEncoding('US-ASCII');
        } catch(InvalidParameterException $ex) {
                echo "Setting server encoding failed: " . $ex->getMessage() . "\n";
                die();
        }

        $mbox_connection->setAttachmentsIgnore(false);

        if (!$mbox_connection->getAttachmentsIgnore()) {
                echo "Save files in: " . $mbox_connection->getAttachmentsDir() . "\n";
        }

        try {
                $mailsIds = $mbox_connection->searchMailbox('SUBJECT "Issue #391"');
        } catch(ConnectionException $ex) {
                die("IMAP connection failed: " . $ex->getMessage());
        } catch (Exception $ex) {
            die("An error occured: " . $ex->getMessage());
        }

        if (empty($mailsIds)) {
                echo "No emails found!\n";
                $mbox_connection->disconnect();
                die();
        }

        echo "Found " . count($mailsIds) . " email(s)...\n";

        $start = microtime(true);

        foreach ($mailsIds as $mailId) {
                echo "+------ P A R S I N G ------+\n";

                $email_content = $mbox_connection->getMail($mailId, false);

                echo "Has attachments? ";
                if($email_content->hasAttachments()) {
                        echo "Yes\n";
                } else {
                        echo "No\n";
                }

                if(!$mbox_connection->getAttachmentsIgnore()) {
                        $attachments = $email_content->getAttachments();

                        echo count($attachments) . " Attachments:\n";

                        foreach ($attachments as $attachment) {
                                echo "- ID: ".$attachment->id.' // CONTENT_ID: '.$attachment->contentId.' // NAME: '.$attachment->name."\n";
                        }
                }
        }

        echo 'time for getting mail Is: '.(microtime(true) - $start).' sec.';
```

I've sent myself an email with 3 `*.eml` files attached as you can see here:

![sample_email_with_multiple_eml_files_attached](https://user-images.githubusercontent.com/5154682/68678449-3e639600-055e-11ea-8c06-a0d2b292d613.png)

When I execute my above code, it finds this email and returns the following:

```bash
> php .\imap-test.php
Trying to connect to '{imap.gmail.com:993/imap/ssl}INBOX'...
Save files in: D:\Sebastian\git\php-imap\files
Found 1 email(s)...
+------ P A R S I N G ------+
Has attachments? Yes
3 Attachments:
- ID: f8676865ce5509432c004edfc7df08c760847f72 // CONTENT_ID:  // NAME: Ticket System Webinterface Korrektur.eml
- ID: c10d9f1500c20cf49aa1cabc8500990bb3fe12b6 // CONTENT_ID:  // NAME: Neuer Test.eml
- ID: 8be017df0e37565076e8ca93a11ba0bca21ced89 // CONTENT_ID:  // NAME: "Ubersetzungen testen.eml
time for getting mail Is: 0.76688408851624 sec.
````

And all of those get saved properly and as expected:

```bash
> dir .\files\

    Verzeichnis: D:\Sebastian\git\php-imap\files

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12.11.2019     15:02           7581 138_8be017df0e37565076e8ca93a11ba0bca21ced89_Ubersetzungen_testen.eml
-a----       12.11.2019     15:02           6209 138_c10d9f1500c20cf49aa1cabc8500990bb3fe12b6_Neuer_Test.eml
-a----       12.11.2019     15:02           7166 138_f8676865ce5509432c004edfc7df08c760847f72_Ticket_System_Webinterface_Korrektur.eml
```

I'll close this issue for now. If you should still face this issue, feel free to comment or reopen this issue. Thanks!

The current latest version 3.0.31 already includes some improvements for the attachments. So it's maybe already fixed with this version.

**Comment by codyproxy** [comment]
Could finally get some time to try this again.

Very strange. I've tried the current latest version (3.0.33), using your exact same example code. For the testing purpose i used a very simple email without images, and 2 mail attachments, also very simple.

Still the same issue:

![mail_content](https://user-images.githubusercontent.com/5427202/69974438-8ce4ce80-1525-11ea-8bd7-5f957303a10f.png)

![code_result](https://user-images.githubusercontent.com/5427202/69974448-92daaf80-1525-11ea-8849-6885169e521a.png)

You can see in my code test result that it results always in 'rfc822.eml', and always 1 file.

In my first screenshot, i accessed my testmail using webmail. You can see that there are 2 email attachments, the webmail automatically called them (translation) 'Part 2.eml' and 'Part 3.eml'

**Comment by jankbrockmann** [comment]
I'm having the same problem. It occurs when I am receiving a mail with multiple attachments and all the attachments having the same name. The resulting attachment-array only has one entry.

**Comment by bapcltd-marv** [comment]
@jankbrockmann does the develop branch exhibit the same issue?

**Comment by jankbrockmann** [comment]
Yes, the same behaviour occurs, when using the develop branch.

**Comment by bapcltd-marv** [comment]
@jankbrockmann have managed to replicate the behaviour (although may be for different reasons).

Currently working on an automated test case.

**Comment by bapcltd-marv** [comment]
#480 includes a fix for multiple identical filenames, but not tested on the original reported issue of multiple .eml attachments.

**Comment by bapcltd-marv** [comment]
tl:dr; [basing the attachment id on the filename of the attachment broke stuff](https://github.com/barbushin/php-imap/pull/480/commits/a46515164a5f568dcece87b62eabf363870e5343)

**Comment by jankbrockmann** [comment]
When may i expect this change to be available the develop branch?

**Comment by jankbrockmann** [comment]
The develop branch works correctly now. All attachments with same name appear in the attachment-array. Waiting for master release :).
